config/scripts: update to master
config: functions, graphic
scripts: build

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -60,10 +60,18 @@ ${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
 # build dependencies, only when PKG_DEPENDS_? is filled
 unset _pkg_depends
 case "${TARGET}" in
-  "target") _pkg_depends="${PKG_DEPENDS_TARGET}";;
-  "host") _pkg_depends="${PKG_DEPENDS_HOST}";;
-  "init") _pkg_depends="${PKG_DEPENDS_INIT}";;
-  "bootstrap") _pkg_depends="${PKG_DEPENDS_BOOTSTRAP}";;
+  "target")
+    _pkg_depends="${PKG_DEPENDS_TARGET}"
+    ;;
+  "host")
+    _pkg_depends="${PKG_DEPENDS_HOST}"
+    ;;
+  "init")
+    _pkg_depends="${PKG_DEPENDS_INIT}"
+    ;;
+  "bootstrap")
+    _pkg_depends="${PKG_DEPENDS_BOOTSTRAP}"
+    ;;
 esac
 
 if is_sequential_build; then
@@ -76,7 +84,7 @@ fi
 if [ "${PKG_SECTION}" = "virtual" ]; then
   PKG_DEEPHASH=$(calculate_stamp)
   for i in PKG_NAME PKG_DEEPHASH BUILD_WITH_DEBUG; do
-    echo "STAMP_${i}=\"${!i}\"" >> ${STAMP}
+    echo "STAMP_${i}=\"${!i}\"" >>${STAMP}
   done
 
   pkg_lock_status "UNLOCK" "${PKG_NAME}:${TARGET}" "build" "built"
@@ -111,7 +119,7 @@ if [ -z "${PKG_TOOLCHAIN}" -o "${PKG_TOOLCHAIN}" = "auto" ]; then
   fi
   _auto_toolchain=" (auto-detect)"
 fi
-if ! listcontains "meson cmake cmake-make configure ninja make autotools manual" "${PKG_TOOLCHAIN}"; then
+if ! listcontains "meson cmake cmake-make configure ninja make autotools manual python-flit python" "${PKG_TOOLCHAIN}"; then
   die "$(print_color "CLR_ERROR" "ERROR:") unknown toolchain ${PKG_TOOLCHAIN}"
 fi
 build_msg "CLR_TOOLCHAIN" "TOOLCHAIN" "${PKG_TOOLCHAIN}${_auto_toolchain}"
@@ -139,8 +147,7 @@ else
   MESON_BUILD_TYPE="plain"
 fi
 
-CMAKE_GENERATOR_NINJA="-GNinja \
-                       -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
+CMAKE_GENERATOR_NINJA="-GNinja"
 
 # configure TARGET build defaults
 TARGET_CONFIGURE_OPTS="--host=${TARGET_NAME} \
@@ -151,9 +158,10 @@ TARGET_CONFIGURE_OPTS="--host=${TARGET_NAME} \
                        --sysconfdir=/etc \
                        --libdir=/usr/lib \
                        --libexecdir=/usr/lib \
-                       --localstatedir=/var \
-                       --disable-static \
-                       --enable-shared"
+                       --localstatedir=/var"
+if flag_enabled "cfg-libs" "yes"; then
+  TARGET_CONFIGURE_OPTS+=" --disable-static --enable-shared"
+fi
 
 TARGET_CMAKE_OPTS="-DCMAKE_TOOLCHAIN_FILE=${CMAKE_CONF} \
                    -DCMAKE_INSTALL_PREFIX=/usr \
@@ -171,7 +179,6 @@ if [ "${BUILD_WITH_DEBUG}" != "yes" ] && flag_enabled "strip" "yes"; then
   TARGET_MESON_OPTS+=" -Dstrip=true"
 fi
 
-
 # configure HOST build defaults
 HOST_CONFIGURE_OPTS="--host=${HOST_NAME} \
                      --build=${HOST_NAME} \
@@ -180,9 +187,10 @@ HOST_CONFIGURE_OPTS="--host=${HOST_NAME} \
                      --sbindir=${TOOLCHAIN}/sbin \
                      --sysconfdir=${TOOLCHAIN}/etc \
                      --libexecdir=${TOOLCHAIN}/lib \
-                     --localstatedir=${TOOLCHAIN}/var \
-                     --disable-static \
-                     --enable-shared"
+                     --localstatedir=${TOOLCHAIN}/var"
+if flag_enabled "cfg-libs:host" "yes"; then
+  HOST_CONFIGURE_OPTS+=" --disable-static --enable-shared"
+fi
 
 HOST_CMAKE_OPTS="${CMAKE_GENERATOR} \
                  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_CONF} \
@@ -227,9 +235,15 @@ cd "${PKG_BUILD}"
 
 if [ -f "${PKG_CONFIGURE_SCRIPT}" -o -f "${PKG_CMAKE_SCRIPT}" -o -f "${PKG_MESON_SCRIPT}" ]; then
   case "${TARGET}" in
-    "target")    PKG_REAL_BUILD="${PKG_BUILD}/.${TARGET_NAME}" ;;
-    "host")      PKG_REAL_BUILD="${PKG_BUILD}/.${HOST_NAME}" ;;
-    "init")      PKG_REAL_BUILD="${PKG_BUILD}/.${TARGET_NAME}-${TARGET}" ;;
+    "target")
+      PKG_REAL_BUILD="${PKG_BUILD}/.${TARGET_NAME}"
+      ;;
+    "host")
+      PKG_REAL_BUILD="${PKG_BUILD}/.${HOST_NAME}"
+      ;;
+    "init")
+      PKG_REAL_BUILD="${PKG_BUILD}/.${TARGET_NAME}-${TARGET}"
+      ;;
     "bootstrap") PKG_REAL_BUILD="${PKG_BUILD}/.${HOST_NAME}-${TARGET}" ;;
   esac
   mkdir -p "${PKG_REAL_BUILD}"
@@ -241,13 +255,13 @@ fi
 # create wrapper scripts in build dir and use them for CC/CXX when
 # building for host and local-cc build flag is set
 if [ "${TARGET}" = "host" ] && flag_enabled "local-cc" "no"; then
-  cat > libreelec-local-cc << EOF
+  cat >libreelec-local-cc <<EOF
 #!/bin/sh
 exec ${CC} "\$@"
 EOF
   chmod +x libreelec-local-cc
   export CC=$(pwd)/libreelec-local-cc
-  cat > libreelec-local-cxx << EOF
+  cat >libreelec-local-cxx <<EOF
 #!/bin/sh
 exec ${CXX} "\$@"
 EOF
@@ -304,19 +318,19 @@ else
     # cmake builds with ninja
     "cmake:target")
       echo "Executing (target): cmake ${CMAKE_GENERATOR_NINJA} ${TARGET_CMAKE_OPTS} ${PKG_CMAKE_OPTS_TARGET} ${PKG_CMAKE_SCRIPT%/*}" | tr -s " "
-      cmake ${CMAKE_GENERATOR_NINJA} ${TARGET_CMAKE_OPTS} ${PKG_CMAKE_OPTS_TARGET} ${PKG_CMAKE_SCRIPT%/*}
+      CMAKE_EXPORT_COMPILE_COMMANDS=1 cmake ${CMAKE_GENERATOR_NINJA} ${TARGET_CMAKE_OPTS} ${PKG_CMAKE_OPTS_TARGET} ${PKG_CMAKE_SCRIPT%/*}
       ;;
     "cmake:host")
       echo "Executing (host): cmake ${CMAKE_GENERATOR_NINJA} ${HOST_CMAKE_OPTS} ${PKG_CMAKE_OPTS_HOST} ${PKG_CMAKE_SCRIPT%/*}" | tr -s " "
-      cmake ${CMAKE_GENERATOR_NINJA} ${HOST_CMAKE_OPTS} ${PKG_CMAKE_OPTS_HOST} ${PKG_CMAKE_SCRIPT%/*}
+      CMAKE_EXPORT_COMPILE_COMMANDS=1 cmake ${CMAKE_GENERATOR_NINJA} ${HOST_CMAKE_OPTS} ${PKG_CMAKE_OPTS_HOST} ${PKG_CMAKE_SCRIPT%/*}
       ;;
     "cmake:init")
       echo "Executing (init): cmake ${CMAKE_GENERATOR_NINJA} ${INIT_CMAKE_OPTS} ${PKG_CMAKE_OPTS_INIT} ${PKG_CMAKE_SCRIPT%/*}" | tr -s " "
-      cmake ${CMAKE_GENERATOR_NINJA} ${INIT_CMAKE_OPTS} ${PKG_CMAKE_OPTS_INIT} ${PKG_CMAKE_SCRIPT%/*}
+      CMAKE_EXPORT_COMPILE_COMMANDS=1 cmake ${CMAKE_GENERATOR_NINJA} ${INIT_CMAKE_OPTS} ${PKG_CMAKE_OPTS_INIT} ${PKG_CMAKE_SCRIPT%/*}
       ;;
     "cmake:bootstrap")
       echo "Executing (bootstrap): cmake ${CMAKE_GENERATOR_NINJA} ${BOOTSTRAP_CMAKE_OPTS} ${PKG_CMAKE_OPTS_BOOTSTRAP} ${PKG_CMAKE_SCRIPT%/*}" | tr -s " "
-      cmake ${CMAKE_GENERATOR_NINJA} ${BOOTSTRAP_CMAKE_OPTS} ${PKG_CMAKE_OPTS_BOOTSTRAP} ${PKG_CMAKE_SCRIPT%/*}
+      CMAKE_EXPORT_COMPILE_COMMANDS=1 cmake ${CMAKE_GENERATOR_NINJA} ${BOOTSTRAP_CMAKE_OPTS} ${PKG_CMAKE_OPTS_BOOTSTRAP} ${PKG_CMAKE_SCRIPT%/*}
       ;;
 
     # cmake builds with make
@@ -338,19 +352,19 @@ else
       ;;
 
     # configure builds
-    "configure:target"|"autotools:target")
+    "configure:target" | "autotools:target")
       echo "Executing (target): ${PKG_CONFIGURE_SCRIPT} ${TARGET_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_TARGET}" | tr -s " "
       ${PKG_CONFIGURE_SCRIPT} ${TARGET_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_TARGET}
       ;;
-    "configure:host"|"autotools:host")
+    "configure:host" | "autotools:host")
       echo "Executing (host): ${PKG_CONFIGURE_SCRIPT} ${HOST_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_HOST}" | tr -s " "
       ${PKG_CONFIGURE_SCRIPT} ${HOST_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_HOST}
       ;;
-    "configure:init"|"autotools:init")
+    "configure:init" | "autotools:init")
       echo "Executing (init): ${PKG_CONFIGURE_SCRIPT} ${INIT_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_INIT}" | tr -s " "
       ${PKG_CONFIGURE_SCRIPT} ${INIT_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_INIT}
       ;;
-    "configure:bootstrap"|"autotools:bootstrap")
+    "configure:bootstrap" | "autotools:bootstrap")
       echo "Executing (bootstrap): ${PKG_CONFIGURE_SCRIPT} ${BOOTSTRAP_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_BOOTSTRAP}" | tr -s " "
       ${PKG_CONFIGURE_SCRIPT} ${BOOTSTRAP_CONFIGURE_OPTS} ${PKG_CONFIGURE_OPTS_BOOTSTRAP}
       ;;
@@ -369,39 +383,56 @@ if pkg_call_exists make_${TARGET}; then
 else
   case "${PKG_TOOLCHAIN}:${TARGET}" in
     # ninja based builds
-    "meson:target"|"cmake:target"|"ninja:target")
+    "meson:target" | "cmake:target" | "ninja:target")
       echo "Executing (target): ninja ${PKG_MAKE_OPTS_TARGET}" | tr -s " "
       ninja ${NINJA_OPTS} ${PKG_MAKE_OPTS_TARGET}
       ;;
-    "meson:host"|"cmake:host"|"ninja:host")
+    "meson:host" | "cmake:host" | "ninja:host")
       echo "Executing (host): ninja ${PKG_MAKE_OPTS_HOST}" | tr -s " "
       ninja ${NINJA_OPTS} ${PKG_MAKE_OPTS_HOST}
       ;;
-    "meson:init"|"cmake:init"|"ninja:init")
+    "meson:init" | "cmake:init" | "ninja:init")
       echo "Executing (init): ninja ${PKG_MAKE_OPTS_INIT}" | tr -s " "
       ninja ${NINJA_OPTS} ${PKG_MAKE_OPTS_INIT}
       ;;
-    "meson:bootstrap"|"cmake:bootstrap"|"ninja:bootstrap")
+    "meson:bootstrap" | "cmake:bootstrap" | "ninja:bootstrap")
       echo "Executing (bootstrap): ninja ${PKG_MAKE_OPTS_BOOTSTRAP}" | tr -s " "
       ninja ${NINJA_OPTS} ${PKG_MAKE_OPTS_BOOTSTRAP}
       ;;
 
     # make based builds
-    "configure:target"|"cmake-make:target"|"autotools:target"|"make:target")
+    "configure:target" | "cmake-make:target" | "autotools:target" | "make:target")
       echo "Executing (target): make ${PKG_MAKE_OPTS_TARGET}" | tr -s " "
       make ${PKG_MAKE_OPTS_TARGET}
       ;;
-    "configure:host"|"cmake-make:host"|"autotools:host"|"make:host")
+    "configure:host" | "cmake-make:host" | "autotools:host" | "make:host")
       echo "Executing (host): make ${PKG_MAKE_OPTS_HOST}" | tr -s " "
       make ${PKG_MAKE_OPTS_HOST}
       ;;
-    "configure:init"|"cmake-make:init"|"autotools:init"|"make:init")
+    "configure:init" | "cmake-make:init" | "autotools:init" | "make:init")
       echo "Executing (init): make ${PKG_MAKE_OPTS_INIT}" | tr -s " "
       make ${PKG_MAKE_OPTS_INIT}
       ;;
-    "configure:bootstrap"|"cmake-make:bootstrap"|"autotools:bootstrap"|"make:bootstrap")
+    "configure:bootstrap" | "cmake-make:bootstrap" | "autotools:bootstrap" | "make:bootstrap")
       echo "Executing (bootstrap): make ${PKG_MAKE_OPTS_BOOTSTRAP}" | tr -s " "
       make ${PKG_MAKE_OPTS_BOOTSTRAP}
+      ;;
+
+    # python builds
+    "python-flit:target")
+      die "$(print_color "CLR_ERROR" "ERROR:") toolchain python-flit should not be used for target!"
+      ;;
+    "python-flit:host")
+      echo "Executing (host): python3 -m flit_core.wheel"
+      DONT_BUILD_LEGACY_PYC=1 python3 -m flit_core.wheel
+      ;;
+    "python:target")
+      echo "Executing (target): python3 -m build -n -w -x ${PKG_PYTHON_OPTS_TARGET}" | tr -s " "
+      python_target_env python3 -m build -n -w -x ${PKG_PYTHON_OPTS_TARGET}
+      ;;
+    "python:host")
+      echo "Executing (host): python3 -m build -n -w -x ${PKG_PYTHON_OPTS_HOST}" | tr -s " "
+      DONT_BUILD_LEGACY_PYC=1 python3 -m build -n -w -x ${PKG_PYTHON_OPTS_HOST}
       ;;
   esac
 fi
@@ -432,35 +463,46 @@ else
 
   case "${PKG_TOOLCHAIN}:${TARGET}" in
     # ninja based builds
-    "meson:target"|"cmake:target")
-      [ "${INSTALL_TO_SYSROOT}" = "yes" ] && \
+    "meson:target" | "cmake:target")
+      [ "${INSTALL_TO_SYSROOT}" = "yes" ] &&
         DESTDIR=${SYSROOT_PREFIX} ninja install ${PKG_MAKEINSTALL_OPTS_TARGET}
       DESTDIR=${INSTALL} ninja install ${PKG_MAKEINSTALL_OPTS_TARGET}
       ;;
-    "meson:host"|"cmake:host")
+    "meson:host" | "cmake:host")
       ninja install ${PKG_MAKEINSTALL_OPTS_HOST}
       ;;
-    "meson:init"|"cmake:init")
+    "meson:init" | "cmake:init")
       DESTDIR=${INSTALL} ninja install ${PKG_MAKEINSTALL_OPTS_INIT}
       ;;
-    "meson:bootstrap"|"cmake:bootstrap")
+    "meson:bootstrap" | "cmake:bootstrap")
       ninja install ${PKG_MAKEINSTALL_OPTS_BOOTSTRAP}
       ;;
 
     # make based builds
-    "configure:target"|"cmake-make:target"|"autotools:target"|"make:target")
-      [ "${INSTALL_TO_SYSROOT}" = "yes" ] && \
+    "configure:target" | "cmake-make:target" | "autotools:target" | "make:target")
+      [ "${INSTALL_TO_SYSROOT}" = "yes" ] &&
         make install DESTDIR=${SYSROOT_PREFIX} -j1 ${PKG_MAKEINSTALL_OPTS_TARGET}
       make install DESTDIR=${INSTALL} ${PKG_MAKEINSTALL_OPTS_TARGET}
       ;;
-    "configure:host"|"cmake-make:host"|"autotools:host"|"make:host")
+    "configure:host" | "cmake-make:host" | "autotools:host" | "make:host")
       make install ${PKG_MAKEINSTALL_OPTS_HOST}
       ;;
-    "configure:init"|"cmake-make:init"|"autotools:init"|"make:init")
+    "configure:init" | "cmake-make:init" | "autotools:init" | "make:init")
       make install DESTDIR=${INSTALL} ${PKG_MAKEINSTALL_OPTS_INIT}
       ;;
-    "configure:bootstrap"|"cmake-make:bootstrap"|"autotools:bootstrap"|"make:bootstrap")
+    "configure:bootstrap" | "cmake-make:bootstrap" | "autotools:bootstrap" | "make:bootstrap")
       make install ${PKG_MAKEINSTALL_OPTS_BOOTSTRAP}
+      ;;
+
+    # python builds
+    "python-flit:target")
+      die "$(print_color "CLR_ERROR" "ERROR:") toolchain python-flit should not be used for target!"
+      ;;
+    "python:target")
+      python3 -m installer --overwrite-existing dist/*.whl -d ${INSTALL} -p /usr
+      ;;
+    "python-flit:host" | "python:host")
+      python3 -m installer --overwrite-existing dist/*.whl
       ;;
   esac
 fi
@@ -516,10 +558,10 @@ if [ "${TARGET}" = "target" -o "${TARGET}" = "init" ]; then
     rm -rf ${INSTALL}/{usr/local/,usr/,}share/zsh
     rm -rf ${INSTALL}/{usr/local/,usr/,}var
     find ${INSTALL} \( -name "*.orig" \
-                  -o -name "*.rej" \
-                  -o -name "*.in" \
-                  -o -name ".git*" \) \
-        -exec rm -f {} \; 2>/dev/null || :
+      -o -name "*.rej" \
+      -o -name "*.in" \
+      -o -name ".git*" \) \
+      -exec rm -f {} \; 2>/dev/null || :
     find ${INSTALL} -type d -exec rmdir -p {} \; 2>/dev/null || :
 
     python_fix_abi "${INSTALL}"
@@ -532,24 +574,24 @@ if [ "${TARGET}" = "target" -o "${TARGET}" = "init" ]; then
         ! -name "libpthread-*.so" \
         ! -name "libthread_db-*so" \
         2>/dev/null) 2>/dev/null || :
-        if [ "${TARGET}" = "init" ]; then
-          ${STRIP} $(find ${INSTALL} -type f -name "*.so*" 2>/dev/null) 2>/dev/null || :
-        fi
-        ${STRIP} $(find ${INSTALL} ! -name "*.so*" ! -name "*.ko" \
-          -type f -executable 2>/dev/null) 2>/dev/null || :
+      if [ "${TARGET}" = "init" ]; then
+        ${STRIP} $(find ${INSTALL} -type f -name "*.so*" 2>/dev/null) 2>/dev/null || :
+      fi
+      ${STRIP} $(find ${INSTALL} ! -name "*.so*" ! -name "*.ko" \
+        -type f -executable 2>/dev/null) 2>/dev/null || :
     fi
   fi
 fi
 
 if [ -n "${INSTALL}" -a -d "${INSTALL}" ]; then
-  echo "INFO_PKG_NAME=\"${PKG_NAME}\"" > "${INSTALL}/.libreelec-package"
+  echo "INFO_PKG_NAME=\"${PKG_NAME}\"" >"${INSTALL}/.libreelec-package"
 fi
 
 cd ${ROOT}
 
 PKG_DEEPHASH=$(calculate_stamp)
 for i in PKG_NAME PKG_DEEPHASH BUILD_WITH_DEBUG; do
-  echo "STAMP_${i}=\"${!i}\"" >> ${STAMP}
+  echo "STAMP_${i}=\"${!i}\"" >>${STAMP}
 done
 
 pkg_lock_status "UNLOCK" "${PKG_NAME}:${TARGET}" "build" "built"
@@ -559,7 +601,7 @@ record_timestamp BUILD_END
 if [ -n "${TRACE_BUILD_TIMING}" ]; then
   (
     print_color "CLR_AUTOREMOVE" "\nBuild timing details:"
-    print_color "CLR_TARGET" "\n================================\n"  
+    print_color "CLR_TARGET" "\n================================\n"
     show_timestamp_diff "unpack" BUILD_BEGIN BUILD_START
     show_timestamp_diff "pre-build setup" BUILD_START BUILD_CONFIGURE
     show_timestamp_diff "configure" BUILD_CONFIGURE BUILD_MAKE
@@ -567,7 +609,7 @@ if [ -n "${TRACE_BUILD_TIMING}" ]; then
     show_timestamp_diff "make install" BUILD_MAKEINSTALL BUILD_COPY_SYSROOT
     show_timestamp_diff "copy sysroot" BUILD_COPY_SYSROOT BUILD_CLEANUP_INSTALL
     show_timestamp_diff "cleanup install" BUILD_CLEANUP_INSTALL BUILD_END
-    print_color "CLR_TARGET" "--------------------------------\n"  
+    print_color "CLR_TARGET" "--------------------------------\n"
     show_timestamp_diff "total time" BUILD_BEGIN BUILD_END
     echo -e
   ) >&${VERBOSE_OUT}
